version: '3.7'

services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: ecommercemssql
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"   
    ports:
      - "1433:1433" 

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-local
    hostname: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672